improve README, move bulk of info to main CrateDB docs
crate/docker-docs pull request #3
Opened 2017-04-25 19:47 UTC by nslater

2017-05-15 11:44 UTC, chaudum requested changes
otherwise ok!

2017-05-15 11:44 UTC, chaudum commented on crate/get-help.md
> +Please report issues via the [GitHub issue tracker](https://github.com/crate/docker-crate/issues).
I would also link the crate/crate repo
Docker related issues should be reported to crate/docker-crate, database issues to crate/crate

2017-05-15 12:17 UTC, chaudum approved these changes

2017-05-16 17:02 UTC, nslater commented
@chaudum some fix ups per feedback from docker. can you re-ack?

2017-05-18 08:47 UTC, chaudum approved these changes

2017-05-19 12:11 UTC, closed without merging

2017-05-19 12:11 UTC, nslater commented
merged in upstream